#! /bin/bash

# Author: Pawel Suder <pawel@suder.info>

[ -r /etc/rc.conf ] && . /etc/rc.conf
[ -r /etc/rc.d/functions ] && . /etc/rc.d/functions

export LOBCDER_USER_DATA_URL=http://169.254.169.254/openstack/latest/user_data
export LOBCDER_SHORT_TOKEN_URL=http://149.156.10.138:8080/lobcder/urest/getshort
export LOBCDER_MOUNT_URL=http://149.156.10.138:8080/lobcder/dav
export LOBCDER_DIR=/media/lobcder

[ -r /etc/conf.d/lobcderd ] && . /etc/conf.d/lobcderd

get_ticket() {
    return $1
}

[ -r /etc/lobcderd/parse_ticket.sh ] && . /etc/lobcderd/parse_ticket.sh

check_if_mounted()
{
    if mount | grep ${LOBCDER_DIR} > /dev/null; then
        return 1
    else
        return 0
    fi
}

mount_lobcder()
{
    export LOBCDER_LONG_TOKEN=`curl ${LOBCDER_USER_DATA_URL} 2>/dev/null`
    export LOBCDER_LONG_TOKEN=`get_ticket ${LOBCDER_LONG_TOKEN}`
    export LOBCDER_TOKEN=`curl ${LOBCDER_SHORT_TOKEN_URL}/${LOBCDER_LONG_TOKEN} 2>/dev/null`
    export COUNTER=10

    if [ ! -d "${LOBCDER_DIR}" ]; then
        mkdir -p ${LOBCDER_DIR}
    fi

    while check_if_mounted && [ ${COUNTER} -gt 0 ]
    do
        echo -n ". "
        echo "user
$LOBCDER_TOKEN
" | mount.davfs ${LOBCDER_MOUNT_URL} ${LOBCDER_DIR} > /dev/null 2>&1
        sleep 1
        let COUNTER=COUNTER-1
    done

    if check_if_mounted
    then
        echo -n "not mounted. "
    else
        echo -n "mounted. "
    fi
}

umount_lobcder()
{
    umount ${LOBCDER_DIR} > /dev/null 2>&1
}

do_start()
{
    check_if_mounted || return 1
    mount_lobcder || return 2
}

do_stop()
{
    check_if_mounted && return 2
    umount_lobcder || return 1
}

start() {
    echo -n "Mounting LOBCDER... "
    do_start
    echo "done."
}

stop() {
    echo -n "Umounting LOBCDER... "
    do_stop
    echo "done."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        stop
        sleep 3
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}"
        exit 3
        ;;
esac
